In [17]:
from xml.etree.ElementPath import prepare_self

import pandas as pd
books=pd.read_csv("books_with_categories.csv")

In [18]:
from transformers import pipeline
classifier=pipeline("text-classification",model="j-hartmann/emotion-english-distilroberta-base",top_k=None,device=-1 )
classifier("I love this!")

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: j-hartmann/emotion-english-distilroberta-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.008528688922524452},
  {'label': 'neutral', 'score': 0.005764589179307222},
  {'label': 'anger', 'score': 0.004419790115207434},
  {'label': 'sadness', 'score': 0.002092392183840275},
  {'label': 'disgust', 'score': 0.001611991785466671},
  {'label': 'fear', 'score': 0.0004138524236623198}]]

In [19]:
books["description"][0]

'9780002005883:A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [20]:
classifier(books["description"][0])

[[{'label': 'fear', 'score': 0.7939406037330627},
  {'label': 'sadness', 'score': 0.08833078294992447},
  {'label': 'neutral', 'score': 0.07640963792800903},
  {'label': 'joy', 'score': 0.016119109466671944},
  {'label': 'surprise', 'score': 0.013414260931313038},
  {'label': 'disgust', 'score': 0.008606516756117344},
  {'label': 'anger', 'score': 0.0031791848596185446}]]

In [21]:
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.6689674854278564},
  {'label': 'joy', 'score': 0.11654406040906906},
  {'label': 'neutral', 'score': 0.09994126856327057},
  {'label': 'fear', 'score': 0.09790413826704025},
  {'label': 'anger', 'score': 0.012247543781995773},
  {'label': 'sadness', 'score': 0.002739887684583664},
  {'label': 'disgust', 'score': 0.0016556266928091645}],
 [{'label': 'neutral', 'score': 0.4493703842163086},
  {'label': 'disgust', 'score': 0.2735915184020996},
  {'label': 'joy', 'score': 0.10908320546150208},
  {'label': 'sadness', 'score': 0.09362740069627762},
  {'label': 'anger', 'score': 0.04047832638025284},
  {'label': 'surprise', 'score': 0.02697017230093479},
  {'label': 'fear', 'score': 0.006879048887640238}],
 [{'label': 'neutral', 'score': 0.6462150812149048},
  {'label': 'sadness', 'score': 0.24273402988910675},
  {'label': 'disgust', 'score': 0.04342275485396385},
  {'label': 'surprise', 'score': 0.028300579637289047},
  {'label': 'joy', 'score': 0.014211492612957954},
  {'label': 'fear', 'score': 0.014084121212363243},
  {'label': 'anger', 'score': 0.011031919158995152}],
 [{'label': 'fear', 'score': 0.9281681180000305},
  {'label': 'anger', 'score': 0.03219105303287506},
  {'label': 'neutral', 'score': 0.012808670289814472},
  {'label': 'sadness', 'score': 0.008756876923143864},
  {'label': 'surprise', 'score': 0.00859791599214077},
  {'label': 'disgust', 'score': 0.008431825786828995},
  {'label': 'joy', 'score': 0.001045584212988615}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104157850146294},
  {'label': 'disgust', 'score': 0.00648059556260705},
  {'label': 'fear', 'score': 0.005393987521529198},
  {'label': 'surprise', 'score': 0.0022869398817420006},
  {'label': 'anger', 'score': 0.001842890284024179},
  {'label': 'joy', 'score': 0.0017338789766654372}],
 [{'label': 'joy', 'score': 0.9327982664108276},
  {'label': 'disgust', 'score': 0.03771696984767914},
  {'label': 'neutral', 'score': 0.015891820192337036},
  {'label': 'sadness', 'score': 0.006444491911679506},
  {'label': 'anger', 'score': 0.005024959798902273},
  {'label': 'surprise', 'score': 0.0015812052879482508},
  {'label': 'fear', 'score': 0.0005423057591542602}],
 [{'label': 'joy', 'score': 0.6528707146644592},
  {'label': 'neutral', 'score': 0.25427478551864624},
  {'label': 'surprise', 'score': 0.06808292120695114},
  {'label': 'sadness', 'score': 0.00990898534655571},
  {'label': 'disgust', 'score': 0.006512219086289406},
  {'label': 'anger', 'score': 0.004821308422833681},
  {'label': 'fear', 'score': 0.0035290136002004147}],
 [{'label': 'neutral', 'score': 0.549476683139801},
  {'label': 'sadness', 'score': 0.1116902306675911},
  {'label': 'disgust', 'score': 0.10400674492120743},
  {'label': 'surprise', 'score': 0.07876548171043396},
  {'label': 'anger', 'score': 0.0641336664557457},
  {'label': 'fear', 'score': 0.051362838596105576},
  {'label': 'joy', 'score': 0.04056441783905029}]]

In [22]:
sentences=books["description"][0].split(".")
predictions=classifier(sentences)

In [23]:
sentences[0]

'9780002005883:A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [24]:
predictions[0]

[{'label': 'surprise', 'score': 0.6689674854278564},
 {'label': 'joy', 'score': 0.11654406040906906},
 {'label': 'neutral', 'score': 0.09994126856327057},
 {'label': 'fear', 'score': 0.09790413826704025},
 {'label': 'anger', 'score': 0.012247543781995773},
 {'label': 'sadness', 'score': 0.002739887684583664},
 {'label': 'disgust', 'score': 0.0016556266928091645}]

In [25]:
predictions

[[{'label': 'surprise', 'score': 0.6689674854278564},
  {'label': 'joy', 'score': 0.11654406040906906},
  {'label': 'neutral', 'score': 0.09994126856327057},
  {'label': 'fear', 'score': 0.09790413826704025},
  {'label': 'anger', 'score': 0.012247543781995773},
  {'label': 'sadness', 'score': 0.002739887684583664},
  {'label': 'disgust', 'score': 0.0016556266928091645}],
 [{'label': 'neutral', 'score': 0.4493703842163086},
  {'label': 'disgust', 'score': 0.2735915184020996},
  {'label': 'joy', 'score': 0.10908320546150208},
  {'label': 'sadness', 'score': 0.09362740069627762},
  {'label': 'anger', 'score': 0.04047832638025284},
  {'label': 'surprise', 'score': 0.02697017230093479},
  {'label': 'fear', 'score': 0.006879048887640238}],
 [{'label': 'neutral', 'score': 0.6462150812149048},
  {'label': 'sadness', 'score': 0.24273402988910675},
  {'label': 'disgust', 'score': 0.04342275485396385},
  {'label': 'surprise', 'score': 0.028300579637289047},
  {'label': 'joy', 'score': 0.014211492612957954},
  {'label': 'fear', 'score': 0.014084121212363243},
  {'label': 'anger', 'score': 0.011031919158995152}],
 [{'label': 'fear', 'score': 0.9281681180000305},
  {'label': 'anger', 'score': 0.03219105303287506},
  {'label': 'neutral', 'score': 0.012808670289814472},
  {'label': 'sadness', 'score': 0.008756876923143864},
  {'label': 'surprise', 'score': 0.00859791599214077},
  {'label': 'disgust', 'score': 0.008431825786828995},
  {'label': 'joy', 'score': 0.001045584212988615}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104157850146294},
  {'label': 'disgust', 'score': 0.00648059556260705},
  {'label': 'fear', 'score': 0.005393987521529198},
  {'label': 'surprise', 'score': 0.0022869398817420006},
  {'label': 'anger', 'score': 0.001842890284024179},
  {'label': 'joy', 'score': 0.0017338789766654372}],
 [{'label': 'joy', 'score': 0.9327982664108276},
  {'label': 'disgust', 'score': 0.03771696984767914},
  {'label': 'neutral', 'score': 0.015891820192337036},
  {'label': 'sadness', 'score': 0.006444491911679506},
  {'label': 'anger', 'score': 0.005024959798902273},
  {'label': 'surprise', 'score': 0.0015812052879482508},
  {'label': 'fear', 'score': 0.0005423057591542602}],
 [{'label': 'joy', 'score': 0.6528707146644592},
  {'label': 'neutral', 'score': 0.25427478551864624},
  {'label': 'surprise', 'score': 0.06808292120695114},
  {'label': 'sadness', 'score': 0.00990898534655571},
  {'label': 'disgust', 'score': 0.006512219086289406},
  {'label': 'anger', 'score': 0.004821308422833681},
  {'label': 'fear', 'score': 0.0035290136002004147}],
 [{'label': 'neutral', 'score': 0.549476683139801},
  {'label': 'sadness', 'score': 0.1116902306675911},
  {'label': 'disgust', 'score': 0.10400674492120743},
  {'label': 'surprise', 'score': 0.07876548171043396},
  {'label': 'anger', 'score': 0.0641336664557457},
  {'label': 'fear', 'score': 0.051362838596105576},
  {'label': 'joy', 'score': 0.04056441783905029}]]

In [26]:
sorted(predictions[0],key=lambda  x: x["label"])

[{'label': 'anger', 'score': 0.012247543781995773},
 {'label': 'disgust', 'score': 0.0016556266928091645},
 {'label': 'fear', 'score': 0.09790413826704025},
 {'label': 'joy', 'score': 0.11654406040906906},
 {'label': 'neutral', 'score': 0.09994126856327057},
 {'label': 'sadness', 'score': 0.002739887684583664},
 {'label': 'surprise', 'score': 0.6689674854278564}]

In [32]:
def calculate_max_emotion_scores(predictions):
    emotion_labels = [
        "anger",
        "disgust",
        "fear",
        "joy",
        "neutral",
        "sadness",
        "surprise"
    ]

    per_emotion_scores = {label: [] for label in emotion_labels}

    for prediction in predictions:
        sorted_predictions = sorted(
            prediction,
            key=lambda x: x["label"]
        )

        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(
                sorted_predictions[index]["score"]
            )

    max_scores = {
        label: max(per_emotion_scores[label])
        for label in emotion_labels
    }

    return max_scores

In [33]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences= books["description"][i].split(".")
    predictions=classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [34]:
emotion_scores

{'anger': [0.0641336664557457,
  0.6126194596290588,
  0.0641336664557457,
  0.351485013961792,
  0.08141247928142548,
  0.23222415149211884,
  0.5381836295127869,
  0.0641336664557457,
  0.2879311442375183,
  0.0641336664557457],
 'disgust': [0.2735915184020996,
  0.3482842445373535,
  0.10400674492120743,
  0.15072223544120789,
  0.18449555337429047,
  0.7271754741668701,
  0.1558547466993332,
  0.10400674492120743,
  0.24911832809448242,
  0.10400674492120743],
 'fear': [0.9281681180000305,
  0.9425276517868042,
  0.9723207950592041,
  0.3607054352760315,
  0.09688025712966919,
  0.051362838596105576,
  0.7474274635314941,
  0.17612971365451813,
  0.9155241250991821,
  0.06394268572330475],
 'joy': [0.9327982664108276,
  0.7517313957214355,
  0.7961245775222778,
  0.5249224901199341,
  0.04056441783905029,
  0.04056441783905029,
  0.7325836420059204,
  0.04056441783905029,
  0.04056441783905029,
  0.058707479387521744],
 'sadness': [0.9671575427055359,
  0.1116902306675911,
  0.1116902306675911,
  0.1116902306675911,
  0.2689116597175598,
  0.1116902306675911,
  0.40800049901008606,
  0.8202820420265198,
  0.36567842960357666,
  0.1116902306675911],
 'surprise': [0.6689674854278564,
  0.252546101808548,
  0.07876548171043396,
  0.07876548171043396,
  0.07876548171043396,
  0.7317203879356384,
  0.11763886362314224,
  0.4650808870792389,
  0.13561373949050903,
  0.09982156753540039],
 'neutral': [0.6462150812149048,
  0.8879393339157104,
  0.549476683139801,
  0.7030516266822815,
  0.8843896985054016,
  0.549476683139801,
  0.7121940851211548,
  0.549476683139801,
  0.8402894735336304,
  0.8603723645210266]}

In [38]:
import tqdm as tqdm
emotion_labels = [
        "anger",
        "disgust",
        "fear",
        "joy",
        "neutral",
        "sadness",
        "surprise"
    ]

isbn=[]
emotion_scores={label:[] for label in emotion_labels}
for i in tqdm.tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences= books["description"][i].split(".")
    predictions=classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5197/5197 [14:45<00:00,  5.87it/s]

In [39]:
emotions_df=pd.DataFrame(emotion_scores)
emotions_df["isbn13"]=isbn

In [40]:
emotions_df

,anger,disgust,fear,joy,neutral,sadness,surprise,isbn13
0,0.064134,0.273592,0.928168,0.932798,0.646215,0.967158,0.668967,9780002005883
1,0.612619,0.348284,0.942528,0.751731,0.887939,0.111690,0.252546,9780002261982
2,0.064134,0.104007,0.972321,0.796125,0.549477,0.111690,0.078765,9780006178736
3,0.351485,0.150722,0.360705,0.524922,0.703052,0.111690,0.078765,9780006280897
4,0.081412,0.184496,0.096880,0.040564,0.884390,0.268912,0.078765,9780006280934
...,...,...,...,...,...,...,...,...
5192,0.148209,0.030643,0.919165,0.255172,0.853721,0.980877,0.030656,9788172235222
5193,0.064134,0.114383,0.051363,0.342498,0.883198,0.111690,0.395507,9788173031014
5194,0.009997,0.009929,0.339218,0.947779,0.375754,0.066685,0.057625,9788179921623
5195,0.064134,0.104007,0.459270,0.759456,0.951104,0.368111,0.078765,9788185300535
5196,0.064134,0.104007,0.051363,0.980873,0.915193,0.111690,0.078765,9789027712059

In [41]:
books=pd.merge(books,emotions_df,on="isbn13")

In [42]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,simple_categories,anger,disgust,fear,joy,neutral,sadness,surprise
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,9780002005883:A NOVEL THAT READERS and critics...,2004.0,3.85,247.0,361.0,Gilead,Fiction,0.064134,0.273592,0.928168,0.932798,0.646215,0.967158,0.668967
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,9780002261982:A new 'Christie for Christmas' -...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,Fiction,0.612619,0.348284,0.942528,0.751731,0.887939,0.111690,0.252546
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"9780006178736:A memorable, mesmerizing heroine...",1993.0,3.93,512.0,29532.0,Rage of angels,Fiction,0.064134,0.104007,0.972321,0.796125,0.549477,0.111690,0.078765
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,9780006280897:Lewis' work on the nature of lov...,2002.0,4.15,170.0,33684.0,The Four Loves,Nonfiction,0.351485,0.150722,0.360705,0.524922,0.703052,0.111690,0.078765
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"9780006280934:""In The Problem of Pain, C.S. Le...",2002.0,4.09,176.0,37569.0,The Problem of Pain,Nonfiction,0.081412,0.184496,0.096880,0.040564,0.884390,0.268912,0.078765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,9788172235222:On A Train Journey Home To North...,2003.0,2.93,324.0,0.0,Mistaken Identity,Nonfiction,0.148209,0.030643,0.919165,0.255172,0.853721,0.980877,0.030656
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,9788173031014:This book tells the tale of a ma...,2002.0,3.70,175.0,24.0,Journey to the East,Nonfiction,0.064134,0.114383,0.051363,0.342498,0.883198,0.111690,0.395507
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,9788179921623:Wisdom to Create a Life of Passi...,2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,Fiction,0.009997,0.009929,0.339218,0.947779,0.375754,0.066685,0.057625
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,9788185300535:This collection of the timeless ...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,Nonfiction,0.064134,0.104007,0.459270,0.759456,0.951104,0.368111,0.078765
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,9789027712059:Since the three volume edition o...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,Nonfiction,0.064134,0.104007,0.051363,0.980873,0.915193,0.111690,0.078765

In [43]:
books.to_csv("books_with_emotions.csv",index=False)